### ISSUE TITLE
Support custom filtering for pre_panic frames

### ISSUE THREAD

**Issue by yaahc** [athre0z/color-backtrace#31] opened 2020-04-29 17:26 UTC
I already added this to my patched version when I was prototyping color-eyre, so I'll open the PR for this, but the idea is to support the following

```rust
            let settings = color_backtrace::Settings::default().add_post_panic_frames(&[
                "<color_eyre::Context as eyre::EyreContext>::default",
                "eyre::",
            ]);
```

**Comment by athre0z** [comment] 2020-04-30 21:33
Duplicate of #25, with a pretty misleading title. I renamed it now, let's continue discussion over there.

**Closed by athre0z** 2020-04-30 21:33 UTC
